const OrderData = [
  {
    orderId: 1,
    transportId: 11,
    customer: "Samppa Nori",
    transporter: "GHN",
    created_at: "2012/01/01",
    status: "Hoàn tất",
    cod: "Thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 2,
    transportId: 10,
    customer: "Estavan Lykos",
    transporter: "GHN",
    created_at: "2012/02/01",
    status: "Đã hủy",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 3,
    transportId: 9,
    customer: "Chetan Mohamed",
    transporter: "GHN",
    created_at: "2012/02/01",
    status: "Đang giao",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 4,
    transportId: 8,
    customer: "Derick Maximinus",
    transporter: "GHN",
    created_at: "2012/03/01",
    status: "Đang xử lý",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 5,
    transportId: 1,
    customer: "Friderik Dávid",
    transporter: "GHN",
    created_at: "2012/01/21",
    status: "Hoàn tất",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 6,
    transportId: 2,
    customer: "Yiorgos Avraamu",
    transporter: "GHN",
    created_at: "2012/01/01",
    status: "Hoàn tất",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 7,
    transportId: 3,
    customer: "Avram Tarasios",
    transporter: "GHN",
    created_at: "2012/02/01",
    status: "Đã hủy",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 8,
    transportId: 4,
    customer: "Quintin Ed",
    transporter: "GHN",
    created_at: "2012/02/01",
    status: "Đang giao",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 9,
    transportId: 1,
    customer: "Enéas Kwadwo",
    transporter: "GHN",
    created_at: "2012/03/01",
    status: "Đang xử lý",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 10,
    transportId: 1,
    customer: "Agapetus Tadeáš",
    transporter: "GHN",
    created_at: "2012/01/21",
    status: "Hoàn tất",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
  {
    orderId: 11,
    transportId: 1,
    customer: "Einar Randall",
    transporter: "GHN",
    created_at: "2012/02/01",
    status: "Đang giao",
    cod: "Không thu",
    cod_price: "200,000 đ",
  },
];

export default OrderData


